# config/meta.yml

meta_product_name: "Inspire"
meta_title: "Inspire me baby !!! - Stay cool, you're Inspired.."
meta_description: "A cool designed toolbox, with a word clickable rhymes and synonyms generator in a real-time text-editor."
meta_image: "cloudy.jpg" # should exist in `app/assets/images/`
twitter_account: "@inspire_account"   # required for Twitter Cards
